function exportfasta(obj, lin)
    % IGREP/EXPORTFASTA Export fasta file for selected lineage
    %
    % EXPORTFASTA(obj, lin) retrieves complete V(D)J nucleotide sequences
    % from database for selected lineage and exports as a fasta file.
    % Population, v-, d- and j-gene calls are included in the annotation
    % lines.  The file name is autogenerated (and written to the current
    % directory): database name (witout the ".db") underscore "lineage"
    % underscore lineageID.
    %
    % Dot notation usage:
    %     D.EXPORTFASTA(12345)
    
    % Chris Fucile
    % Alex Rosenberg
    % 5 August 2025
    % University of Alabama at Birmingham
    % Department of Biomedical Informatics and Data Science
    % and UAB Immunology Institute
    % Copyright (c) 2025. All rights reserved.
    % This software is offered with no guarantees of any kind.
    
    r = query(obj, [...
        'SELECT sequenceID, population, Vgene, Dgene, Jgene, ',...
        'NT_VDJ FROM Sequence WHERE lineageID = ' num2str(lin)]);
    
    h = ">" + r.sequenceID + "|" + r.population + "|" + r.Vgene + "|" + r.DGene + "|" + r.JGene;
    s = r.NT_VDJ;
    t = [h s]';
    t = t(:);
    fid = fopen([regexprep(obj.dbname, '.db', '') '_lineage_',...
        num2str(lin) '.fasta'], 'w');
    fprintf(fid, '%s\n', t{:});
    fclose(fid);
end      
