function exportinfo(obj, lin)
    % IGREP/EXPORTINFO Export database rows for particular lineage
    %
    % EXPORTINFO(obj, lin) retrieves rows from database for selected
    % lineage and writes to a tab-delimited text file.  The file name is
    % autogenerated (and written to the current directory): database name
    % (witout the ".db") underscore "lineage" underscore lineageID.
    %
    % Dot notation usage:
    %     D.EXPORTINFO(12345)  
            
    % Chris Fucile
    % Alex Rosenberg
    % 5 August 2025
    % University of Alabama at Birmingham
    % Department of Biomedical Informatics and Data Science
    % and UAB Immunology Institute
    % Copyright (c) 2025. All rights reserved.
    % This software is offered with no guarantees of any kind.
            
    % pr = query(obj, 'PRAGMA table_info(Sequence)');
    f = string(sqlfind(obj.handle, 'sequence').Columns{1}');

    % remove all the base-to-base transition column in the IMGT 8 file
    f = f(cellfun('isempty', regexp(f, '[CDR1|CDR2|CDR3|FR1|FR2|FR3|V]_[acgt]')));

    % query
    q = [...
        'SELECT ' char(strjoin(f, ', ')) ' FROM Sequence ',...
        'WHERE lineageID = ' num2str(lin)];
    r = query(obj, q);

    % write to file
    fname = [regexprep(obj.dbname, '.db', '') '_lineage_', num2str(lin) '.txt'];
    writetable(r, fname, 'Delimiter', '\t', 'WriteRowNames', true);            
end
